### ISSUE TITLE
YARP and iCub installers do not accept the /D argument

### ISSUE THREAD

**Issue by drdanz** [robotology/robotology.github.io#16]
According to nsis documentation [[1](http://nsis.sourceforge.net/Docs/Chapter3.html)], for installers generated with NSIS:

> /D sets the default installation directory ($INSTDIR), overriding InstallDir and InstallDirRegKey. It must be the last parameter used in the command line and must not contain any quotes, even if the path contains spaces. Only absolute paths are supported.

Unfortunately this does not work for YARP and iCub installers, and they always run with "C:\Program Files\robotology' as the default folder. This makes it impossible to change the installation destination when executing it with /S from the command line.

NSIS v2.46 that is used for the builds according to the installer, was released in 2009 [[2](https://sourceforge.net/projects/nsis/files/NSIS%202/2.46/)], perhaps in that version the /D argument was not supported, but I cannot find any documentation about.

I suggest to upgrade the NSIS to the latest version when we will generate the next version of the packages. If we are not doing anything strange in the packaging script, this might fix this issue. @mbrunettini what do you think?

**Comment by drdanz** [comment]
Actually according to the changelog, /D was already available in NSIS 2.25, see http://nsis.sourceforge.net/nightly/Docs/AppendixF.html#v2.25
So perhaps we are doing something strange?

**Comment by pattacini** [comment]
Perhaps it'd be worth moving this issue to [robotology/icub-packaging](https://github.com/robotology/icub-packaging).

**Comment by vtikha** [comment]
Why do we even support windows?? 😛

**Comment by mbrunettini** [comment]
moved to https://github.com/robotology/icub-packaging/issues/6
