### ISSUE TITLE
IFI Younglings Assignment 5

### ISSUE THREAD

**Issue by vtikha** [robotology/robotology.github.io#18]
Dear @robotology/ifi-younglings & @kompky

We have been silent for a while but we are back on track to tackle the **fifth** and **final** assignment 😉.
The idea for this one is to introduce you to **scripting** and **execution** of **non-interactive** (pre-programmed) demos. This is useful if you want to quickly program **behaviors** while doing some interaction experiments or for tv interviews, shows, and videos. 

For the next **IFI Day (23/03/17)** you will be asked to prepare a **pre-programmed demo** as if we, @robotology/ifi-masters, were **interviewing the iCub**. The responses should include, arm/leg movements, emotions, and speech, and be self-explanatory. You are free to improvise 😉 

The interview will consist of the following questions/remarks and each of them will require a response:

>1. Hi iCub! So happy to finally meet you!
>1. What does your name mean?
>1. How old are you?
>1. Who are you? describe yourself to me (DoF, emotions, skin)
>1. Do you have any brothers or sisters?
>1. Tell me a little bit about what you can do.
>1. Why was it important to build you similar to a human being? 
>1. What are the challenges of artificial intelligence?
>1. Who is better iCub or R1?
>1. Thank you iCub for your time

To help you along with this task have a look at the scripts located in [`funny-things`](https://github.com/robotology/funny-things/tree/master/app/scripts/shells) and create your own for this specific assignment (do not commit it in `funny-things` 😉 )

Tutors will have to supervise their younglings and give them hints on how to accomplish things but if there are still problems do (not) hesitate to contact us 😄 

See you at the next IFI Day!
cc @robotology/ifi-padawans @robotology/ifi-knights @robotology/ifi-masters

**Comment by S-Dafarra** [comment]
Does the robot need to "understand" the question? :grin:

**Comment by alecive** [comment]
Is there still time for me to participate? :grinning:

**Comment by GiuliaP** [comment]
You have to find a tutor ;)

**Comment by giuliavezzani** [comment]
@Arya07, @gmmarconi and @Iaxama, don't leave the robot on and in strange poses if you are at the canteen! :scream: :wink:

**Comment by pattacini** [comment]
It's been very funny to assist your demonstrations 😃 
Well done lads!
