### ISSUE TITLE
Members promoted

### ISSUE THREAD

**Issue by pattacini** [robotology/robotology.github.io#19]
Because they're good fellows and we can count on them, @Arya07 @gmmarconi @Iaxama @S-Dafarra @gabrielenava are now trained members of @robotology/ifi-padawans.

cc @robotology/ifi-knights @robotology/ifi-masters 

🏅 🎉 ✨ 🍻

**Comment by pattacini** [comment]
cc @robotology/ifi-knights @robotology/ifi-masters

**Comment by apaikan** [comment]
congratulations 🙏

**Comment by Iaxama** [comment]
What an honor! We will not let you down :trophy: :tada:

**Comment by vtikha** [comment]
congrats 🏅🏅🏅🏅🏅 👏

**Comment by pattacini** [comment]
By the way, @Iaxama I've just got a task for you, as a brand new padawan...

![joking](https://media.giphy.com/media/3ohA2VFobX1jQ2mMJG/giphy.gif)

**Comment by Iaxama** [comment]
I'm ready for the task :wink: (in case you are not joking :smile: )

**Comment by barbalberto** [comment]
Yeah!!! Congratulations!!
Now we can assign you all robotology issues!! 

![gpt](https://www.mememaker.net/static/images/memes/4456025.jpg)

**Comment by pattacini** [comment]
Unfortunately I was joking, but keep yourself ready 😉
