### ISSUE TITLE
Test custom ipopt can be replaced with version from debian/ubuntu repositories

### ISSUE THREAD

**Issue by drdanz** [robotology/robotology.github.io#3]
We should test if custom ipopt can be replaced with version from debian/ubuntu repositories and eventually remove it from icub-common

**Comment by drdanz** [comment]
@pattacini Can you please remind me which one was the ipopt test?

**Comment by pattacini** [comment]
It's the smoke test within the icub-tutorials repo.

**Comment by pattacini** [comment]
We should put the directive `ADD_DEFINITIONS(${IPOPT_DEFINITIONS})` in any `CMakeLists.txt` file whose binary links against `Ipopt`.

**Comment by drdanz** [comment]
On Debian Jessie (3.11.9-2) it works if `-DHAVE_CSTDDEF` is added to `CMAKE_CXX_FLAGS`

On Ubuntu Trusty (coinor-ipopt  3.11.4-1build1) the default version does not work, therefore for now we are stuck with our version at least until April 2016.

**Comment by drdanz** [comment]
The `icub-common` package currently includes ipopt. We should aim at using the system version for the versions that support it, and gradually get rid of our version.
- [x] Fix the pkg-config files in the `icub-common` package (paths of files in `/usr/lib/pkgconfig/*.pc` are wrong. CC @mbrunettini
- [x] Fix the `FindIpopt.cmake` file in [icub-main](https://github.com/robotology/icub-main) (and in [ycm](https://github.com/robotology/ycm) to use `pkg-config` (we should ensure that it works with custom ipopt builds)
- [ ] Remove the custom ipopt build for the working versions and replace it with a dependency to coinor-libipopt-dev

**Comment by pattacini** [comment]
done with `add_definitions()` and the extension of `CMAKE_EXE_LINKER_FLAGS` variable.

**Comment by mbrunettini** [comment]
Fixed the wrong path in the pkg-config files, new package for version 1.1.16 will be  available soon

**Comment by drdanz** [comment]
@traversaro noticed that `-DHAVE_CSTDDEF` is required on debian/ubuntu systems due to a patch in debian package, not in ace itself.

**Comment by traversaro** [comment]
icub-main updated to use the system ipopt in : https://github.com/robotology/icub-main/pull/340 .

**Comment by traversaro** [comment]
```
Unpacking icub-common (1.1.17-1~xenial) ...
dpkg: error processing archive /var/cache/apt/archives/icub-common_1.1.17-1~xenial_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/libipopt.so.1', which is also in package coinor-libipopt1v5 3.11.9-2.1
Selecting previously unselected package javascript-common.
Preparing to unpack .../javascript-common_11_all.deb ...
Unpacking javascript-common (11) ...
Processing triggers for doc-base (0.10.7) ...
Processing 2 added doc-base files...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for install-info (6.1.0.dfsg.1-5) ...
Processing triggers for libglib2.0-0:amd64 (2.48.0-1ubuntu4) ...
Errors were encountered while processing:
 /var/cache/apt/archives/icub-common_1.1.17-1~xenial_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Apparently `icub-common` should conflict also with `coinor-libipopt1v5`.

**Comment by mbrunettini** [comment]
custom IPOPT have been removed on linux packages starting from release 1.4
