### ISSUE TITLE
IFI Day 4 on 27/11/2015

### ISSUE THREAD

**Issue by pattacini** [robotology/robotology.github.io#8]
Hi @robotology/all-robotology-developers, 

On `November 27` we are going to run our **IFI Day 4** event.

**IFI** stands for **`I-Fix-the-Issues`** and with that we aim to collect long-standing issues we then try to attack and solve all in one day. This type of event takes place on a **monthly** basis (roughly).

So far, we already run 3 IFI events internally and we ended up having lots of fun and a quite decent number of issues fixed. Therefore, to increase that amount and spread the fun, starting with the **IFI Day 4** we want to make this happening **open to whoever is willing to participate**.

Thus, if you are eager to contribute, simply join us that day (remotely :smirk:) or even the days before and/or wave your hand here too, so that it will be easier for us to manage your distant help. For example, we could set up a [**Cloud9 IDE**](https://c9.io) for live interaction.

Also, to give you a flavor of the workflow we use to handle the issues, look at the bottom picture:

[![kanban](https://cloud.githubusercontent.com/assets/3738070/11362615/2e2520c8-9295-11e5-8c5d-860c53e9c848.jpg)](https://waffle.io/robotology/robotology.github.io)

That's a screenshot of the [**Kanban boards**](https://en.wikipedia.org/wiki/Kanban_board) we can generate as a view over our GitHub repositories by means of the [**Waffle**](https://waffle.io) tool.

Here follow the pipelines we employ:
- **New**: any time an issue is created it goes automatically in this board.
- **Backlog**: we group up here those issues that have been somehow inspected by one developer.
- **IFI Day**: we identify within this board those issues we'd like to solve during IFI days.
- **In Progress**: whenever a developer starts working out an issue, this should be notified and the issue gets moved in this pipeline.
- **Feedback**: once the issue is solved, it should be put under this board so that others can inspect that everything was done properly.

How can we generate and maintain this beautiful summary in an automatic fashion? We make use of **GitHub labels** of course :smiley:, and in particular, by simply assigning the following labels, all the issues will get handled seamlessly through the boards:

[![backlog](https://cloud.githubusercontent.com/assets/3738070/11363185/840220d8-9298-11e5-9cd6-ba2716642ec7.PNG)](https://github.com/robotology/robotology.github.io/labels)
[![ifi](https://cloud.githubusercontent.com/assets/3738070/11363191/8c45ef18-9298-11e5-9014-25fcf4a1c6a7.PNG)](https://github.com/robotology/robotology.github.io/labels)
[![progress](https://cloud.githubusercontent.com/assets/3738070/11363192/8f2a7bd6-9298-11e5-8be5-fbad7feefc9b.PNG)](https://github.com/robotology/robotology.github.io/labels)
[![feedback](https://cloud.githubusercontent.com/assets/3738070/11363197/921e97dc-9298-11e5-8080-c92387b772e0.PNG)](https://github.com/robotology/robotology.github.io/labels)

To this end, the GitHub repositories that are organized with **Waffle** need to sport those labels.

Finally, to also highlight that a specific issue is currently under inspection during the **IFI Day <n>**, we assign it to the corresponding **GitHub milestone**. To grab all the solved issues, including those solved right on the last bell of the day, we tend to set their due date equal to the day after :smirk: (to avoid messing up the _Burndown charts_).

You can also follow **IFI Day** events on our _G+ community_:
[![iCub Research](http://ssl.gstatic.com/images/icons/gplus-32.png)](https://plus.google.com/u/0/communities/116897884020660435466?prsrc=3)

Post below any question you might have ...
... and :sparkles: enjoy debugging all together! :sparkles: :smirk:

**Comment by pattacini** [comment]
For IIT developers: we are going to meet up in _Marconi_ room this Friday.

**Comment by apaikan** [comment]
cool :)

**Comment by serena-ivaldi** [comment]
nice tool this Waffle!

**Comment by traversaro** [comment]
@pattacini  Some developers of our group ( @robotology/codyco-developers ) are willing to participate but their expertise is more on some of our projects rather then on YARP, so I wonder if it could be possible to add https://github.com/robotology/idyntree to the waffle board?

**Comment by pattacini** [comment]
Done!
I've created the **IFI Day 4** milestone too as well as the required labels.

**Comment by traversaro** [comment]
Perfect :+1:

**Comment by serena-ivaldi** [comment]
Hi guys, how do you organize tomorrow? Is it the whole day? How does it work? 
I surely cannot free the whole day (one meeting and HRI experiments going on) but I would like to know more how we can contribute from remote (consider that we do not have the iCub here yet). In particular I would like to get my students involved as well, though I don't know how precisely.

**Comment by Tobias-Fischer** [comment]
Hi guys,
I'm not sure whether I'll have some spare time tomorrow, as there are still some things to do for the integration meeting next week. However I'll get in touch in case I have a few hours to tackle some issues :).
I'll definitely try to participate in future IFI days though, as said before the idea is great and it helps the whole community.

Best, Tobi

**Comment by pattacini** [comment]
Hi @serena-ivaldi,

Cool!
Yep, the event will be run throughout the whole day, more or less, though there's no need to provide a constant presence, of course.

We have a large bunch of issues visible in **Waffle**, hence I think you could simply pick up those you deem are most suitable to you and **follow the policies** detailed above. If you have no clue, we could maybe suggest some.

Please don't forget to proceed via **Pull Requests** (aka PR).

@Tobias-Fischer that's great!

Happy debugging!

**Comment by pattacini** [comment]
I've prepared this [**Cloud9 IDE**](https://ide.c9.io/pattacini/ifi-day) for interactive programming, if needed.

**Comment by traversaro** [comment]
@serena-ivaldi 
A relatively simple issue is : https://github.com/robotology/gazebo-yarp-plugins/issues/154 . 

All those methods are variant of methods that are already implemented, and so they should be easy to implement by just calling and/or copyng code from their "variant". It is necessary to understand what a yarp "controlboard" and what Gazebo is, but I think that would be something that your student should learn anyway.
